# Generated by Django 5.2.5 on 2026-08-29 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=500, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='integration',
            name='base_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integration',
            name='encrypted_credentials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='encrypted_oauth_state',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='provider_type',
            field=models.CharField(choices=[('gitlab', 'GitLab'), ('generic_oauth', 'Generic OAuth MCP'), ('generic_custom', 'Generic custom MCP')], default='generic_custom', max_length=32),
        ),
        migrations.AddField(
            model_name='integration',
            name='write_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integration',
            name='remote_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.URLField(max_length=1000)),
                ('resource', models.URLField(max_length=1000)),
                ('code_challenge', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('resource', models.URLField(max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('resource', models.URLField(max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
