# Generated by Django 5.2.5 on 2026-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_oauthclient_integration_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='family_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
