# Generated by Django 5.2.5 on 2026-08-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='integration',
            name='gateway_unique_user_slug',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='user',
        ),
        migrations.AlterField(
            model_name='integration',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='gateway.workspace'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='gateway_unique_workspace_slug'),
        ),
    ]
