# Generated by Django 5.2.5 on 2026-08-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_enforce_workspace_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polar_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('polar_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='gateway.workspace')),
            ],
        ),
    ]
