# Generated by Django 5.2.5 on 2026-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_polarwebhookevent_billingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polarwebhookevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
