# Generated by Django 5.2.5 on 2026-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_billingaccount_last_event_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=48)),
                ('identifier_hash', models.CharField(max_length=64)),
                ('window', models.PositiveBigIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'identifier_hash', 'window'), name='gateway_unique_rate_limit_bucket')],
            },
        ),
    ]
