# Generated by Django 5.2.5 on 2026-08-31 14:24

from django.db import migrations, models
import gateway.providers


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_ratelimitbucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider_type',
            field=models.CharField(choices=gateway.providers.provider_choices, default='generic_custom', max_length=32),
        ),
    ]
