# Generated by Django 5.2.5 on 2026-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_ratelimitbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='scope',
            field=models.CharField(default='mcp:read', max_length=48),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='scope',
            field=models.CharField(default='mcp:read', max_length=48),
        ),
        migrations.AddField(
            model_name='oauthrefreshtoken',
            name='scope',
            field=models.CharField(default='mcp:read', max_length=48),
        ),
    ]
