# Generated by Django 5.2.17 on 2026-08-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_alter_integration_provider_type'),
        ('gateway', '0010_oauthaccesstoken_scope_oauthauthorizationcode_scope_and_more'),
    ]

    operations = [
    ]
