# Generated by Django 5.2.5 on 2026-08-30 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_key', models.TextField(blank=True)),
                ('signed_document', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('grace_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('organization', models.CharField(max_length=200)),
                ('entitlements', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('bound_instance_id', models.UUIDField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
